[WIP] meta/QA
berserktech/ideas pull request #16
Opened 2019-02-22 05:01 UTC by sadasant

Idea de nuestras reuniones semanales sobre preguntas y respuestas.
Por favor comentar.

Para participar directamente, por favor utilizar `git` directamente o la UI de GitHub.
Si necesitan permiso para editar, me dicen y les doy permiso.

2019-02-22 19:00 UTC, zeitan requested changes

2019-02-22 19:00 UTC, zeitan commented on meta/QA/CHANGELOG.md
> +- Definicion de idea/QA
Definición, se puede acentuar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/README.md
> +## Definicion
Definición, se puede acenturar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/README.md
> +Cada `NOTAS.md` tendra la siguiente estructura (o parecido):
tendrá, se puede acentuar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/README.md
> +- Daniel Rodriguez
Rodríguez, se puede acentuar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/AUTHORS
> +Daniel Rodriguez <sadasant@gmail.com>
Rodríguez, se puede acentuar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/README.md
> +Reunion semanal para hacernos preguntas y respuestas entre nosotros.
Reunión, se puede acentuar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/README.md
> +- [Puntos tratados, de forma cronologica]
cronológica, se puede acentuar?

2019-02-22 19:00 UTC, zeitan commented on meta/QA/reuniones/2019-02-23/NOTAS.md
> +- Daniel Rodriguez
Rodríguez, se puede acentuar?

2019-02-24 15:37 UTC, iamjinme approved these changes
Importante indicar que existe un calendario con la descripción de la reunión en http://bit.ly/2GI976n

2019-02-24 18:02 UTC, zeitan approved these changes
LGTM

2019-02-26 15:05 UTC, merged