WIP: información inicial del proyecto de vacas humanitarias
berserktech/ideas pull request #17
Opened 2019-02-24 08:53 UTC by sebasmagri

2019-02-24 15:04 UTC, sadasant requested changes
Antes que nada: GENIAL! Muchísimas gracias por esta idea.

Ahora, sobre el formato:
- Este PR necesita estos dos archivos: CHANGELOG.md y AUTHORS.

Por ahora, CHANGELOG.md solo con:
```
# 0.0.0
* Idea [categoría]/[nombre-del-proyecto] creada.
```

Y el AUTHORS solo con tu nombre.

2019-02-24 20:09 UTC, ghostbar commented
¿Es básicamente un GoFundMe enfocado en Venezuela? @sebasmagri

2019-02-24 23:06 UTC, ghostbar approved these changes
Me gusta. Ya discutimos roadmap y todo en Telegram. Por ahí se puede empezar.

2019-02-25 16:57 UTC, zeitan requested changes

2019-02-25 16:57 UTC, zeitan commented on proyectos/plataforma-vaca-humanitaria/AUTHORS
> +Sebastián Magrì <sebasmagri@gmail.com>
acento quedo al revés  el acento en la "ï" de tu apellido

2019-02-25 16:57 UTC, zeitan commented on proyectos/plataforma-vaca-humanitaria/CHANGELOG.md
> +# 0.0.1
no debería ser todo 0.0.1 ?

2019-03-02 10:30 UTC, sebasmagri commented
> ¿Es básicamente un GoFundMe enfocado en Venezuela? @sebasmagri

Para referencia futura, referirse a la propuesta, pero ya fue discutido en qué difiere de las plataformas de crowdfunding existentes.

2019-03-03 17:20 UTC, zeitan approved these changes
LGTM
:1st_place_medal:

2019-03-07 17:37 UTC, sadasant approved these changes

2019-03-13 20:22 UTC, milmazz reviewed
@sebasmagri Excelente iniciativa, te dejo algunos comentarios.

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +social que ayuden a paliar este tipo de situaciones in situ.
```suggestion
social que ayuden a paliar este tipo de situaciones en el lugar.
```

Medio _nitpick_ la vaina, pero, _in situ_ es un latinismo, por lo tanto deberia escribirse en cursivas, pero, considero que es más claro cambiarlo por: "en el sitio".

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +# Plataforma Crowd de ayuda humanitaria
```suggestion
# Plataforma pública de ayuda humanitaria
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +imposibilidad de obtener los elementos para cubrir sus necesidades más
```suggestion
imposibilidad de cubrir sus necesidades
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +asociaciones, ONGs, grupos religiosos, entre otros, para solicitar
```suggestion
asociaciones, organizaciones no gubernamentales (ONGs), grupos religiosos, entre otros, para solicitar
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +quirúrgicas de mayor costo, y que en muchos de estos mismos casos no
```suggestion
quirúrgicas de mayor costo, los cuales en muchos casos no
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +    este tipo para obtener donacionese en línea y fuera de línea,
```suggestion
    este tipo para obtener donaciones en línea y fuera de línea,
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +    las actividades de organizaciones y/o individuales, así como
```suggestion
    las actividades de organizaciones o individuos, así como
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +    hora de brindar apoyo, debido a que existen pocas garantías de que
```suggestion
    hora de brindar apoyo, debido a las pocas garantías que
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  debido a carencias de tiempo, complejidad de las plataformasxs
```suggestion
  debido a carencias de tiempo, complejidad de las plataformas
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  materiales, los mismos muchas veces son redundantes, no orientados a
```suggestion
  materiales, los mismos muchas veces son redundantes, no están orientados a
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  las necesidades reales, o sencillamente no de la calidad esperada.
```suggestion
  las necesidades reales, o sencillamente no tienen la calidad esperada.
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +- Iniciativas locales sin apoyo: existen iniciativas in situ, que
```suggestion
- Iniciativas locales sin apoyo: existen iniciativas en sitio, que
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +similares casi en cada uno de los casos en que existen situaciones de
```suggestion
similares en muchos casos en los cuales existen situaciones de
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +Implementar una plataforma concentradora de apoyo para iniciativas de
```suggestion
Implementar una plataforma que reuna el apoyo para iniciativas de
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  *pote* centralizado.
```suggestion
  fondo o *pote* centralizado.
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  para realizar donaciones en dinero, sea de manera periódica como de
```suggestion
  para realizar donaciones en dinero, ya sean recurrentes o
```

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  finales en un sistema de intercambio digital. Véase [Building
_Building Blocks_ en cursiva.

2019-03-13 20:22 UTC, milmazz commented on proyectos/plataforma-vaca-humanitaria/README.md
> +  asignación de beneficios desde el *pote*.
Yo dejaría de usar la palabra _pote_ pues creo que no es neutral, en el supuesto caso que esto lo lea alguien que no sea venezolano.

2019-03-17 08:25 UTC, sebasmagri commented
@milmazz le puedes dar una revisada de nuevo? :-)

2019-03-25 14:22 UTC, milmazz commented
@sebasmagri LGTM 👍

2024-10-13 06:36 UTC, sadasant approved these changes

2024-10-13 06:36 UTC, merged