proyectos(linea-del-tiempo): información inicial
berserktech/ideas pull request #18
Opened 2019-02-24 10:13 UTC by sebasmagri

Proyecto de creación de una línea del tiempo digital sobre la historia (inicialmente la contemporánea) de Venezuela, aunque igualmente se pueda extrapolar.

[Rendered](https://github.com/sebasmagri/ideas/blob/proyecto/the-venezuela-timeline/proyectos/the-venezuela-timeline/README.md)

2019-02-24 14:51 UTC, sadasant requested changes
Antes que nada: GENIAL! Muchísimas gracias por esta idea.

Ahora, sobre el formato:
- Este PR necesita estos dos archivos: CHANGELOG.md y AUTHORS.

Por ahora, CHANGELOG.md solo con:
```
# 0.0.0
* Idea [categoría]/[nombre-del-proyecto] creada.
```

Y el AUTHORS solo con tu nombre.

2019-02-24 18:08 UTC, zeitan requested changes

2019-02-24 18:08 UTC, zeitan commented on proyectos/the-venezuela-timeline/examples/e0.dot
> +  # base example events
nit: Could be those comments in Spanish?

2019-02-24 18:08 UTC, zeitan commented on proyectos/the-venezuela-timeline/AUTHORS
> +Sebastián Magrì <sebasmagri>
could add your full contact here? email?

2019-02-24 18:08 UTC, zeitan commented on proyectos/the-venezuela-timeline/CHANGELOG.md
> +* Dump inicial de información de la idea
podrias modificar la palabra "dump" por algún equivalente en español?

2019-02-24 19:58 UTC, ghostbar approved these changes
Me encanta :-D

2019-02-25 01:34 UTC, edgar commented
Excelente iniciativa!

2019-02-25 16:53 UTC, zeitan commented on proyectos/the-venezuela-timeline/CHANGELOG.md
> +# 0.0.1
nit: solo curiosidad, por que cada commit se convierte en una versión si este PR no ha sido mergeado? no debería ser tood esto 0.0.1?

2019-02-25 16:54 UTC, zeitan commented on proyectos/the-venezuela-timeline/AUTHORS
> +Sebastián Magrì <sebasmagri@gmail.com>
creo que el acento quedo al reves aquí

2019-02-25 16:55 UTC, zeitan commented on proyectos/the-venezuela-timeline/CHANGELOG.md
> +* Descarga inicial de información de la idea
que te parece "Creada la información inicial de la idea" ?

2019-02-26 16:03 UTC, sadasant commented on proyectos/the-venezuela-timeline/CHANGELOG.md
> +# 0.0.1
100% de acuerdo, @zeitan

2019-02-28 03:56 UTC, satanas approved these changes
😈

2019-03-03 17:21 UTC, zeitan approved these changes

2019-03-06 06:03 UTC, satanas commented
¿Cuántos reviews necesitamos para mergear la idea?

2019-03-06 16:01 UTC, sadasant approved these changes

2019-03-06 18:24 UTC, asdrubalivan approved these changes

2019-03-06 18:26 UTC, merged

2019-03-06 19:24 UTC, fmontes reviewed
Cooool!