First edit made with qinab.com :)
berserktech/ideas pull request #29
Opened 2019-03-11 10:46 UTC by guerrerocarlos

https://qinab.com/berserktech/ideas/blob/master/meta/manifesto/doc/Manifesto.md

2019-03-12 13:42 UTC, guerrerocarlos commented
Extended PR to include README notes about including economic indicators in the timeline.

2019-03-15 20:36 UTC, sebasmagri approved these changes

2019-03-17 16:46 UTC, guerrerocarlos commented
Solicitando PR Reviewers por aqui 🙏

2019-03-17 16:59 UTC, sebasmagri requested changes
Te dejé por ahí unos comentarios. Veo cambios en el formato markdown que me imagino que vienen de qinab. No tengo ningún problema con adoptar ese formato/estilo, pero deberíamos usar PRs por separado y documentar una guía de estilo que se ajuste al output de qinab.

2019-03-17 16:59 UTC, sebasmagri commented on meta/manifesto/doc/Manifesto.md
> +Without further ado, let us be and continue being how we all are, and let’s see what we can do with a little push to do something together once again.
No sé si sería mejor separar los cambios al Manifesto en su PR.

2019-03-17 16:59 UTC, sebasmagri commented on proyectos/internet-alternativo/README.md
> +Centro de redes ULA: <https://internethalloffame.org/inductees/ermanno-pietrosemoli>
Hay unos enlaces actualizados acá en la discusión

2019-03-17 16:59 UTC, sebasmagri commented on proyectos/internet-alternativo/README.md
> +-   SDR - Software Designed Radio
s/designed/defined

2019-03-17 16:59 UTC, sebasmagri commented on proyectos/internet-alternativo/README.md
> +-   SDN - Software Designed Network
idem

2019-03-17 17:36 UTC, guerrerocarlos commented on meta/manifesto/doc/Manifesto.md
> +Without further ado, let us be and continue being how we all are, and let’s see what we can do with a little push to do something together once again.
La próxima vez hago PRs separados.

2019-03-17 17:37 UTC, guerrerocarlos commented on proyectos/internet-alternativo/README.md
> +Centro de redes ULA: <https://internethalloffame.org/inductees/ermanno-pietrosemoli>
donde no los veo :(

2019-03-17 17:37 UTC, guerrerocarlos commented on proyectos/internet-alternativo/README.md
> +-   SDR - Software Designed Radio
corregido

2019-03-17 17:37 UTC, guerrerocarlos commented on proyectos/internet-alternativo/README.md
> +-   SDN - Software Designed Network
corregido

2019-03-17 17:40 UTC, guerrerocarlos commented
Comentarios corregidos, dejaré un solo PR por esta vez, la próxima vez haré PRs separados por documento.

Activé commonMark en qinab.com para que sigamos con la misma sintaxis que ya veníamos.
https://github.com/guerrerocarlos/qinab.com/blob/master/markdownEngine/htmlmd.js#L14

2019-03-18 09:15 UTC, sebasmagri commented on proyectos/internet-alternativo/README.md
> +Centro de redes ULA: <https://internethalloffame.org/inductees/ermanno-pietrosemoli>
en la [sección de antecedentes](https://github.com/orgs/berserktech/teams/internet-alternativo/discussions/6)

2019-03-18 14:49 UTC, closed without merging

2019-03-18 14:50 UTC, guerrerocarlos commented
Preferible seguirlo llevando todo aqui:
https://github.com/orgs/berserktech/teams/internet-alternativo/