Nuestro Manifesto
berserktech/ideas pull request #9
Opened 2019-02-16 23:35 UTC by sadasant

Usé este método: https://medium.com/@macropus/export-your-medium-posts-to-markdown-b5ccc8cb0050

Fixes #8

2019-02-17 00:17 UTC, asdrubalivan approved these changes

2019-02-17 00:21 UTC, zeitan requested changes

2019-02-17 00:21 UTC, zeitan commented on meta/manifesto/README.md
> +# Manifesto
Cambia esto a ingles digo  para que coincida readme y manifesto

2019-02-21 00:20 UTC, zeitan requested changes

2019-02-21 00:20 UTC, zeitan commented on meta/manifesto/CHANGELOG.md
> +* Idea meta/manifesto creada.
change to english

2019-02-21 00:24 UTC, zeitan approved these changes
LGTM :kiss:

2019-02-21 00:32 UTC, merged